config/routes.rb
Rails.application.routes.draw do
  get 'favorites/update'
  get 'favorites', to: 'favorites#index'
  devise_for :users
  root to: 'pages#home'
  get 'dogs/map', to: 'dogs#map'

  resources :dogs do
    resources :bookings, only: [ :new, :create, :show ]
  end

  resources :users, only: [ :show ] do
    resources :reviews, only: [ :new, :create ]
    get '/profile', to: 'users#profile'
    get '/dashboard', to: 'users#dashboard'
  end

  resources :bookings, only: [ :index ] do
    member do
      get :accept
      get :reject
    end

  end

  resources :bookings, only: [ :show ] do
    resources :chatrooms, only: [ :create]
  end

  resources :chatrooms, only: [ :show ] do
    resources :messages, only: :create
  end

  resources :chatrooms, only: [ :index]

end

app/models/dog.rb
class Dog < ApplicationRecord
  has_one_attached :photo
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :favorites, dependent: :destroy
  validates :name, :size, :age, :description, :gender, :address, :breed, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :search_by_breed_and_size_and_gender,
    against: [ :breed, :size, :gender ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  before_action :set_dog, only: [:show, :update]
  protect_from_forgery except: :index

  def index

    if params[:query].present?
      @dogs = Dog.search_by_breed_and_size_and_gender(params[:query])
    else
      @dogs = Dog.all
    end

    # the `geocoded` scope filters only flats with coordinates (latitude & longitude)
    @markers = @dogs.geocoded.map do |dog|
      {
        lat: dog.latitude,
        lng: dog.longitude,
        info_window: render_to_string(partial: "dog_map_infos", locals: { dog: dog }),
        image_url: helpers.asset_url("dog_icon.jpg")
      }
    end

    respond_to do |format|
      format.js {
        return render partial: 'dogs/list', locals: { dogs: @dogs }
      }
      format.html # go do your thing
    end

    #render the index page by default
  end

  def map
  end

  def show
    @booking = Booking.new
    @favorite_exist = Favorite.where(dog: @dog, user: current_user) == [] ? false : true
  end

  def new
    @dog = Dog.new
  end

  def create
    @dog = Dog.new(dog_params)
    @dog.user = current_user
    if @dog.save
      redirect_to dogs_path
    else
      render :new
    end
  end

  def update
    # @dog = Dog.find(params[:id]) before-action inplace
    if @dog.update(dog_params)
      redirect_to dog_path(@dog)
    else
      render :show
    end
  end

  private

  def set_dog
    @dog = Dog.find(params[:id])
  end

  def dog_params
    params.require(:dog).permit(:name, :size, :age, :description, :gender, :address, :breed, :photo)
  end

end

app/views/dogs/_dog_infos.html.erb
<div class="dog-card" data-controller="edit-dog" data-edit-dog-target="card">
  <%= image_tag dog.photo, height: 300, width: 400, crop: :fill%>
  <div class="dog-infos <%= 'd-none' if dog.errors.any? %>" data-edit-dog-target="infos">
    <h2 title="<%= dog.name %> (<%= dog.age %>)">
      <%= dog.name %><small>(<%= dog.age %>)</small>
    </h2>
    <i class="fas fa-pen fa-xs ml-2" data-action="click->edit-dog#displayForm"></i>
  </div>

  <%= simple_form_for dog, html: { class: dog.errors.any? ? '' : 'd-none', data: { edit_dog_target: 'form', action: 'submit->edit-dog#update' } } do |f| %>
    <%= f.input :name %>
    <%= f.input :age %>
    <%= f.submit "Update dog", class: "btn btn-sm btn-primary btn-block mt-2" %>
  <% end %>
</div>

app/views/dogs/_dog_map_infos.html.erb
  <%= image_tag dog.photo, height: 150, width: 200, crop: :fill%>
    <h2><%= dog.name %></h2>
    <h4> <i class="fas fa-dog fas-large"></i><%= dog.breed %></h4>
    <h5 class="address-text"> <i class="fas fa-home fas-large"></i><%=  dog.address %></h5>
    <div class="btn-width">
      <%= link_to ' 🐾 Choose me! 🐾', dog_path(dog), class: "btn btn-flat", width:200, crop: :fill %>
    </div>
  </div>
</div>

app/views/dogs/_list.html.erb
<div data-search-dogs-target="list">

  <div class="dogs-container">
    <% dogs.each do |dog| %>
      <div class="dog-trip">
        <div class="hearticon">
          <i class="fab fa-gratipay"></i>
        </div>
        <%= cl_image_tag dog.photo.key, height: 300, width: 400, crop: :fill, class: "dog-image" %>
        <div class="details-container">
          <div class="namecolor">
            <h2><%= dog.name %></h2>
          </div>
          <div>
            <div class="dog-detail-text">
              <h4> <i class="fas fa-dog fas-large"></i><%= dog.breed %></h4>
              <p class="address-text"> <i class="fas fa-home fas-large"></i><%=  dog.address %></p>
            </div>
            <div class="button-center">
              <%= link_to 'Choose me!', dog_path(dog), class: "btn btn-flat" %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/dogs/index.html.erb
<div class="profile-wrapper">

  <%= render 'shared/side_navbar' %>

  <div class="bio-wrapper">

    <div data-controller="search-dogs">
    <h1>Poochies List</h1>
      <div class="index-search-container">
        <div class="search-map-layout">
          <div class="search-bar">
            <%= form_with url: dogs_path, method: :get, html: { class:
            'mb-4', data: { search_dogs_target: 'form' } } do |f| %>
            <%= f.text_field :query,
                      class: "form-control",
                      placeholder: 'Search for breed, gender or size (small, medium or large)',
                      value: params[:query],
                      data: { search_dogs_target: 'input', action: 'keyup->search-dogs#update' } %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="map-card-container">
        <%= render 'list', dogs: @dogs %>
        <div class="map" style="width: 50%; height: 100vh;"
          data-controller="mapbox"
          data-mapbox-markers-value="<%= @markers.to_json %>"
          data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dogs/new.html.erb
<div class="profile-wrapper">
  <%= render 'shared/side_navbar' %>
  <div class="bio-wrapper container">

    <h1 class="titlefont">Add Your Dog</h1>
    <hr>
    <div class="form-container">
      <%= simple_form_for(@dog) do |f| %>
        <%= f.input :name, placeholder: "Herbert" %>
        <%= f.input :breed, placeholder: "Jack Russel" %>
        <%= f.input :address, placeholder: "10 Downing Street, LONDON, SW1A 2AA" %>
        <%= f.input :age, placeholder: "Years"%>
        <%= f.input :gender, collection: ['Female', 'Male'], as: :radio_buttons %>
        <%= f.input :size, collection: ['Small', 'Medium', 'Large'], as: :radio_buttons %>
        <%= f.input :description, placeholder: "Happy dog that likes..."  %>
        <%= f.input :photo, input_html: { class: "hidden" } %>
        <%= f.submit value: "Add Dog" %>
      <% end %>
    </div>
  </div>
</div>

app/views/dogs/placeholder.html.erb
<div class="showpagecontainer">
  <% if @dog.user_id == current_user.id %>
    <h3> I own the dog</h3>
    <div class="dogowner">
      <div data-controller="edit-dog">
        <div class="container">
          <div class="dog-container">
            <div class="dog-img mr-5">
              <%= cl_image_tag @dog.photo.key, height: 300, width: 400, crop: :fill %>
            </div>
            <div class="dog-card" data-edit-dog-target='info'>
              <div id="dog-name">
                <h5><%= @dog.name %></h5>
                <h5><%= @dog.breed %></h5>
              </div>
              <div class="attrib-container">
                <div>
                  <h5>Size: <%= @dog.size %></h5>
                  <h5>Age: <%= @dog.age %></h5>
                  <h5>Description: <%= @dog.description %></h5>
                </div>
                <div>
                  <h5>Gender: <%= @dog.gender %> </h5>
                  <h5>Address: <%= @dog.address %></h5>
                  <h5>Likes: <%=  @dog.likes %></h5>
                </div>
              </div>
            </div>
          </div>
              <%= button_tag "Edit", class:"btn btn-primary edit-btn", data: { action: "click->edit-dog#displayForm" } %>
              <%= simple_form_for @dog, html: { class: "#{'d-none' unless @dog.errors.any?}",  data: { edit_dog_target: 'form'} } do |f| %>
                <%= f.input :name %>
                <%= f.input :breed %>
                <%= f.input :size %>
                <%= f.input :age %>
                <%= f.input :description %>
                <%= f.input :gender %>
                <%= f.input :address %>
                <%= f.submit "Update dog", class: "btn btn-sm btn-primary btn-block mt-2" %>
              <% end %>
        </div>
      <div>
    </div>

    <% else %>
    <%= cl_image_tag @dog.photo.key, height: 300, width: 400, crop: :fill %>
      <h5>Name: <%= @dog.name %></h5>
      <h5>Breed: <%= @dog.breed %></h5>
      <h5>Size: <%= @dog.size %></h5>
      <h5>Age: <%= @dog.age %></h5>
      <h5>Description: <%= @dog.description %></h5>
      <h5>Gender: <%= @dog.gender %> </h5>
      <h5>Address: <%= @dog.address %></h5>
      <h5>Likes: <%=  @dog.likes %></h5>
      <%= simple_form_for([@dog, @booking]) do |f| %>
            <%= f.input :start_date, as: :date, html5: true%>
            <%= f.input :end_date, as: :date, html5: true%>
            <%= f.submit class: "btn-flat btn-flat:hover" %>
      <% end %>
    <% end %>

</div>

app/views/dogs/show.html.erb
<div class="profile-wrapper">

  <%= render 'shared/side_navbar' %>

  <div class="bio-wrapper container">
    <div class="container-dogshow">
      <div class="dog-info-show">
        <%= cl_image_tag @dog.photo.key, height: 300, width: 400, crop: :fill %>


        <%= link_to favorites_update_path(dog: @dog), id:'favorite_link', remote: true  do %>
        <i class="fab fa-gratipay fa-2x <%= favorite_class %>" id='favorite-link'></i>
        <% end %>

        <div class="show-container-text">
          <h2><%=  @dog.name %></h2>
          <p><i class="fas fa-dog fas-large"></i><%= @dog.breed %></p>
            <p><i class="fas fa-home fas-large"></i><%= @dog.address %></p>
          <div class="icons-show">
            <p><%= @dog.size.capitalize %></p> |
            <p>Age: <%= @dog.age %></p> |
            <% if @dog.gender == "female" %>
              <p><i class="fas fa-venus fas-lg-card"></i></p>
            <% else %>
              <p><i class="fas fa-mars fas-lg-card"></i></p>
            <% end %>
            </div>
            <p>Doggy Bio: <%= @dog.description %></p>

              <div class="owner-box">
                <%= cl_image_tag @dog.user.photo.key, class: "avatar-bordered" %>
                <p>Owner: <%=  link_to @dog.user.first_name, user_profile_path(@dog.user) %></p>
              </div>


          </div>
        </div>
        <%# Booking form %>
        <div class="dog-booking-show">
          <h3>Book This Poochy</h3>
            <%= simple_form_for([@dog, @booking]) do |f| %>
              <%= f.input :start_date, as: :date, html5: true%>
              <%= f.input :end_date, as: :date, html5: true%>
              <%= f.submit class: "btn-flat btn-flat:hover create-bookbtn", value: "Book me!" %>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>