config/routes.rb
Rails.application.routes.draw do
  get 'favorites/update'
  get 'favorites', to: 'favorites#index'
  devise_for :users
  root to: 'pages#home'
  get 'dogs/map', to: 'dogs#map'

  resources :dogs do
    resources :bookings, only: [ :new, :create, :show ]
  end

  resources :users, only: [ :show ] do
    resources :reviews, only: [ :new, :create ]
    get '/profile', to: 'users#profile'
    get '/dashboard', to: 'users#dashboard'
  end

  resources :bookings, only: [ :index ] do
    member do
      get :accept
      get :reject
    end

  end

  resources :bookings, only: [ :show ] do
    resources :chatrooms, only: [ :create]
  end

  resources :chatrooms, only: [ :show ] do
    resources :messages, only: :create
  end

  resources :chatrooms, only: [ :index]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  has_one_attached :photo

  has_many :bookings, dependent: :destroy
  has_many :dogs, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :chatrooms, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :messages, dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @dogs = Dog.where(user_id: @user)
    @review = Review.new
  end

  def profile
     @user = User.find(params[:user_id])
     @review = Review.new

  end

  def dashboard
    @user = User.find(params[:user_id])
    @dogs = Dog.where(user_id: @user)
  end
end

app/views/users/_reviews.html.erb
<%# Show reviews section Only if the profile is about a walker %>
<% if !@user.owner %>

  <%# REVIEWS LIST %>
  <div id="reviews">
    <% if @user.reviews.blank? %>
      <p>No reviews yet</p>
    <% else %>
      <% @user.reviews.each do |review| %>
        <h4 id="review-<%= review.id %>"><%= review.content %></h4>
        <h5><% review.rating.times do%>
        <i class="fas fa-star"></i>
        <% end %>
        </h5>
        <hr>
      <% end %>
    <% end %>
  </div>


  <%# REVIEW FORM %>
  <% if @user != current_user %>
    <div class="text-center">
      <h2>Leave a review</h2>
      <%= simple_form_for([@user, @review], remote: true) do |f| %>
        <%= f.input :content, placeholder: "What did you like? What could be done better?", class: "form-control-review" %>
        <%= f.input :rating, collection: (1..5).to_a, label: "Rate this Walker" %>
        <%= f.submit "Send review", class: "btn btn-flat btn-review" %>
      <% end %>
    </div>
  <% end %>

<% end %>

app/views/users/dashboard.html.erb
<div class="profile-wrapper">
  <%= render 'shared/side_navbar' %>
  <div class="bio-wrapper container">

    <% if !current_user.owner %>
      <h1></h1>
      <h1>My Dog Bookings</h1>
      <h2><%= "You haven't booked any dogs yet!" if @user.bookings.empty? %></h2>
      <% @user.bookings.each do |booking| %>
        <div class="notification">
          <div class="notification-content">
            <p><small>From <%= booking.start_date.strftime("%b %d, %Y") %> to <%= booking.end_date.strftime("%b %d, %Y") %></small></p>
            <p>Requested Dog:<%=link_to booking.dog.name, dog_path(booking.dog)%> | Owned by:<%=link_to booking.dog.user.first_name, user_profile_path(booking.dog.user)%> </p>
          </div>
            <%# CHAT BUTTON %>
            <% chatroom = Chatroom.where(booking_id: booking.id) %>
            <%= link_to "Send a Message", chatroom_path(chatroom[0]), id: "send-button"%>
          <div class="notification-actions">

            <%if booking.confirmed %>
              <p>Status of Request: Accepted</p>
            <% else %>
              <p>Status of Request: Pending</p>
            <% end %>
          </div>
        </div>
        <hr>
      <% end %>
    <% else %>

    <%# User is a Owner %>
    <h1></h1>
    <h1>My Dog Bookings</h1>
    <% @user.dogs.each do |dog| %>
      <% dog.bookings.each do |booking| %>
        <div class="notification">
          <%= cl_image_tag  booking.user.photo.key, class: "avatar-large avatar-bordered" %>
          <div class="notification-content">
            <p><small>From <%= booking.start_date.strftime("%b %d, %Y") %> to <%= booking.end_date.strftime("%b %d, %Y") %></small></p>
            <p>Requested Dog:<%=link_to booking.dog.name, dog_path(booking.dog)%> | Walker Name:<%=link_to booking.user.first_name, user_profile_path(booking.user_id)%></p>
          </div>
            <%# CHAT BUTTON %>
            <% chatroom = Chatroom.where(booking_id: booking.id) %>
            <%= link_to "Send a Message", chatroom_path(chatroom[0]), id: "send-button"%>
          <%if booking.confirmed %>
          <div class="notification-actions">
            <h4>Status: Accepted</h4>
          </div>
          <% else %>
          <div class="notification-actions">
            <%= link_to accept_booking_path(booking), method: :get, remote: :true do %>
              <i class="fas fa-check-circle fa-3x"></i>
            <% end %>
            <%= link_to reject_booking_path(booking), method: :get, remote: :false do %>
            <i class="fas fa-times-circle fa-3x"></i>
            <% end %>
          </div>
          <% end %>
        </div>
        <hr>
      <% end %>
    <% end %>

      <%# Show dogs %>
    <h1>My Dogs</h1>

    <div class="dogs-container">
      <% @dogs.each do |dog| %>
        <div class="dog-trip">
          <%= cl_image_tag dog.photo.key, height: 300, width: 400, crop: :fill, class: "dog-image" %>
          <div class="details-container">
            <div class="namecolor">
              <h2><%= dog.name %></h2>
            </div>
            <div>
              <div class="dog-detail-text">
              <p class="breed-text"> <i class="fas fa-dog fas-large"></i><%= dog.breed %></p>
              <p class="age-text"> <i class="fas fa-paw fas-large"></i><%=  dog.age %> years old</p>
            </div>
            <div class="button-center">
              <%= link_to 'My Poochy', dog_path(dog), class: "btn btn-flat" %>
            </div>
          </div>
         </div>
        </div>
      <% end %>
    </div>
    <% end %>
  </div>
</div>

app/views/users/profile.html.erb
<div class="profile-wrapper">
  <%= render 'shared/side_navbar' %>
  <div class="bio-wrapper container">

      <div class="titleprofile my-3 text-left">
        <h1>My Profile</h1>
      </div>

    <%# BOTSRAP CARD BIO%>
    <div class="profile-card">
        <div class="profile-avatar img">
          <div class='text-center'>
          <%= cl_image_tag @user.photo.key %>
            <h5 class="card-title"><%= @user.first_name %> <%= @user.last_name %> </h5>
            <p class="card-text-email"><small> <%= @user.email %></small></p>
          <p class="card-text-email"><small>Member since <%= @user.created_at.strftime("%b %d, %Y") %></small></p>
          </div>
        </div>
          <div class="description-card">
            <h2 class="reviewfont"> <strong>About Me</strong></h2>
            <p class="card-title-role"><%= @user.owner ? 'I am a dog owner' : 'I am a dog walker' %> and <%= @user.description %></p>


          <% if !@user.owner %>

            <h2 class="reviewfont"><strong>Poochies walked</strong> (<%= @user.poochies %>)</h2>
            <% @user.poochies.times do %>
            <span>🐶</span>
            <% end %>
          <% end %>
    </div>
  </div>
    <% if !@user.owner %>
      <div class="container profile-card review-container">
        <h1 class="reviewfont">Reviews</h1>
        <div>
          <p> <%= render 'reviews' %> </p>
        </div>
      </div>
    <% end %>
</div>
</div>

app/views/users/show.html.erb
<h1><%= @user.first_name %> <%= @user.last_name %> - Dashboard</h1>

<% if @user.dogs.empty? %>
<h1>My Dog Bookings</h1>
<h2><%= "You haven't booked any dogs yet!" if @user.bookings.empty? %></h2>
<div class="card-grid">
 <% @user.bookings.each do |booking| %>
  <div class="card-trip">
        <%= cl_image_tag @dog.photo.key%>
    <div class="card-trip-infos">
        <%= link_to booking.dog.name, dog_path(booking.dog) %>
        <p>from: <%= booking.start_date %></p>
        <p>to: <%= booking.end_date %></p>
        <% if booking.confirmed == false %>
           <p>Status of Booking: Pending</p>
        <% else%>
           <p>Status of Booking: Accepted</p>
        <% end%>
      </div>
    </div>
  </div>
</div>
<% end %>


<h1>My Reviews</h1>


<p>_________________________________________________________</p>

<% else %>

  <h1>My Dogs</h1>
  <% @dogs.each do |dog| %>
    <%= cl_image_tag dog.photo.key, height: 300, width: 400, crop: :fill %>
    <p> Name: <%= dog.name %></p>
    <p> Size: <%= dog.size %></p>
    <p> Age: <%=  dog.age %></p>
    <p> Description: <%=  dog.description %></p>
    <p> Likes: <%=  dog.likes %></p>
    <p> Address: <%=  dog.address %></p>
    <p> Gender: <%=  dog.gender%></p>
  <% end %>


<h1>My Booking Requests</h1>
  <% if @user == current_user %>
  <% @user.dogs.each do |dog| %>
    <% dog.bookings.each do |booking| %>
      <p>Name: <%= link_to 'go', user_profile_path(booking.user_id) %>
      <%= @user.first_name %> <%= @user.last_name %> </p>
      <p>From: <%= booking.start_date %> to <%=booking.end_date %>
      <p>Description: I am a 24 y old dog lover</p>
      <p>Number of walks: 4 <%= @user.poochies %></p>
      <p>Email: <%= @user.email %></p>
      <%if booking.confirmed %>
        <p>Status of Request: Accepted</p>
      <% else %>
        <%= link_to "Accept", accept_booking_path(booking), method: :get, remote: :true, class: "btn-flat"%>
        <%= link_to "Decline", reject_booking_path(booking), method: :get, remote: :false, class: "btn-flat"%>
      <% end %>
    <p> __________________</p>
    <% end %>
  <% end %>

<% end %>
<% end %>


<hr>
<%# REVIEW FORM %>

<div id="reviews">
  <% if @user.reviews.blank? %>
    <p>Be the first to leave a review for <%= @user.first_name %></p>
  <% else %>
    <% @user.reviews.each do |review| %>
      <p id="review-<%= review.id %>"><%= review.content %></p>
      <p>Stars: <%= review.rating %></p>
      <hr>
    <% end %>
  <% end %>
</div>

<h1>Leave a review</h1>
  <div class="container">
    <div class="row">
      <div class="col-xs-4">
        <%= simple_form_for([@user, @review], remote: true) do |f| %>
          <%= f.input :content %>
          <%= f.input :rating, collection: (1..5).to_a, label: "Rate this Walker" %>
          <%= f.submit "Send your review" %>
        <% end %>
      </div>
    </div>
  </div>