config/routes.rb
Rails.application.routes.draw do
  get 'favorites/update'
  get 'favorites', to: 'favorites#index'
  devise_for :users
  root to: 'pages#home'
  get 'dogs/map', to: 'dogs#map'

  resources :dogs do
    resources :bookings, only: [ :new, :create, :show ]
  end

  resources :users, only: [ :show ] do
    resources :reviews, only: [ :new, :create ]
    get '/profile', to: 'users#profile'
    get '/dashboard', to: 'users#dashboard'
  end

  resources :bookings, only: [ :index ] do
    member do
      get :accept
      get :reject
    end

  end

  resources :bookings, only: [ :show ] do
    resources :chatrooms, only: [ :create]
  end

  resources :chatrooms, only: [ :show ] do
    resources :messages, only: :create
  end

  resources :chatrooms, only: [ :index]

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    © <strong>Poochy App</strong>
  </div>
</div>

app/views/shared/_navbar.html.erb
<%# <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.1/css/all.css" crossorigin="anonymous"> %>

<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
  <div class="navlogo">
    <%= image_tag "logo_nav.png",id: "navlogo1" %>
    <%= image_tag "poochy_nav.png",class: "navlogo2" %>
  </div>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <div class="username">
          <h6><%= current_user.first_name.capitalize %> <%= current_user.last_name.capitalize %></h6>
        </div>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle navbar-avatar avatar-bordered", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Chat", "#", class: "dropdown-item" %>
            <%= link_to "Profile", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_side_navbar.html.erb
<div class="side-nav">

    <%= link_to user_profile_path(current_user)	do %>
    <i class="fas fa-user-circle fa-2x"></i>
    <% end %>

    <%= link_to user_dashboard_path(current_user)	do %>
      <i class="fas fa-archive fa-2x"></i>
    <% end %>

    <% if current_user.owner %>

      <%= link_to new_dog_path	do %>
      <i class="fas fa-plus-square fa-2x"></i>
      <% end %>

    <% else %>

      <%= link_to dogs_path	do %>
      <i class="fas fa-dog fas-large fa-2x"></i>
      <% end %>

      <%= link_to favorites_path	do %>
      <i class="fas fa-heart fa-2x"></i>
      <% end %>

    <% end %>

    <%= link_to chatrooms_path do %>
      <i class="fas fa-comments fa-2x"></i>
    <% end %>



  </div>